### ISSUE TITLE
Notes on Doing a Shift Training - Shift Overview

### ISSUE THREAD

**Issue by DakotaLMartinez** [cassaram09/technical-coach-training#1]
### Sync

Maybe at the end it would be nice to say that if you run out of time with a student and you're not at a good stopping point, you can let them know that you're happy to put them back in the queue and have another coach come on to help them in a minute. After ending your share, you can do `qbot more help` in slack and the question will be automatically reassigned.

## Slack Channels - Flatiron Staff

We should mention the #virtualbox channel here as well. It has a bunch of useful pinned items, links to available resources, videos and the github docs with fixes to the most common known issues.

## Resources

I know this is in progress, just wanted to make sure I plugged the technical coach resources repo as well :)

**Comment by cassaram09** [comment]
Good stuff, thanks!
